### ISSUE TITLE
Q: Would it be possible to molrender an MVSJ file?

### ISSUE THREAD

**Issue by zachcp** [molstar/molrender#14]
I am wondering how difficult it would be to render a [molviewspec](https://molstar.org/mol-view-spec/) JSON file. This would be a really nice utility that would extend the value of the MVS system.

**Comment by dsehnal** [comment]
This is already possible https://molstar.org/mol-view-spec-docs/mvs-molstar-extension/#command-line-utilities

**Comment by zachcp** [comment]
That is fanstastic. Thank you @dsehnal .

**Comment by zachcp** [comment]
( posting issues on the main repo: https://github.com/molstar/molstar/issues/1123 )
