### ISSUE TITLE
Assemblies from crystallographic symmetry are not colored with distinct colors

### ISSUE THREAD

**Issue by josemduarte** [molstar/molrender#6]
E.g. 1fs6 

https://cdn.rcsb.org/images/structures/1fs6_assembly-1.jpeg

Is there a specific reason for assemblies not to be colored with the "Chain instance" preset instead?

**Comment by dsehnal** [comment]
This https://github.com/molstar/molrender/blob/999004467b017b7e6ab2fc9ac183efe1c182a621/src/render.ts#L93 seems to be the function that decides the default theme. Perhaps we can easily tweak that.

**Comment by josemduarte** [comment]
It looks like after all images were regenerated with v0.5.2, this is now solved (see image linked above). So it seems that this issue had actually been solved in previous commits, it's only that the images were generated with an earlier version, possibly v0.3.0 or around there.
